# Generated by Django 3.2.25 on 2024-05-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_listofcountries_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofcountries',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
