# Generated by Django 3.2.25 on 2024-05-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_listofcountries_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='regions',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
