# Generated by Django 3.2.25 on 2024-06-14 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20240614_1629'),
        ('ordersapp', '0002_auto_20240527_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('FM', 'Формируется'), ('STP', 'Отправлен в обработку'), ('PRD', 'Оплачен'), ('PD', 'Обрабатывается'), ('RDY', 'Подтверждён размещением'), ('CNL', 'Отменён')], default='FM', max_length=3, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.accommodation', verbose_name='Размещение'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='nights',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
