# Generated by Django 3.2.25 on 2024-06-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_alter_basket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='add_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='nights',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во ночей'),
        ),
    ]
