# Generated by Django 3.2.25 on 2024-05-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_traveluser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveluser',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
