# Generated by Django 3.2.25 on 2024-05-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_traveluser_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traveluser',
            options={},
        ),
    ]
