# Generated by Django 3.2.25 on 2024-05-27 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_traveluser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traveluser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
