# Generated by Django 3.2.25 on 2024-05-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_traveluser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveluserprofile',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
