# Generated by Django 3.2.25 on 2024-06-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_traveluserprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveluser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='users_avatars', verbose_name='аватар'),
        ),
    ]
